# SwiftLint Configuration for Internet Archive Apple TV
# Configured for legacy codebase modernization (Swift 4.0 -> 6.2)

# Paths to include in linting
included:
  - Internet Archive

# Paths to exclude from linting
excluded:
  - Pods
  - DerivedData
  - .build
  - vendor

# Enabled rules (start with essential rules for legacy code)
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Disabled rules (too strict for legacy codebase initially)
disabled_rules:
  - todo # Allow TODOs during migration
  - line_length # Will enable after initial cleanup
  - type_body_length # Legacy ViewControllers are large
  - file_length # Legacy files may exceed limits
  - function_body_length # Will refactor in later sprints
  - cyclomatic_complexity # Will address in refactoring phase
  - trailing_whitespace # Minor issue, fix later

# Rule configurations
force_cast:
  severity: warning # Downgrade to warning during migration

force_try:
  severity: warning

force_unwrapping:
  severity: warning # Critical for safety but warning during migration

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - j
    - x
    - y
    - vc
    - nc

type_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 50
    error: 60

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

large_tuple:
  warning: 3
  error: 4

# Reporter type (xcode for Xcode integration)
reporter: "xcode"

# Custom rules for legacy codebase migration
custom_rules:
  deprecated_didreceivememorywarning:
    name: "Deprecated didReceiveMemoryWarning"
    regex: 'didReceiveMemoryWarning\(\)'
    message: "didReceiveMemoryWarning() is deprecated. Remove this method."
    severity: warning

  deprecated_uiapplicationlaunchoptionskey:
    name: "Deprecated UIApplicationLaunchOptionsKey"
    regex: 'UIApplicationLaunchOptionsKey'
    message: "Use UIApplication.LaunchOptionsKey instead"
    severity: error

  deprecated_nsattributedstringkey:
    name: "Deprecated NSAttributedStringKey"
    regex: 'NSAttributedStringKey\.'
    message: "Use NSAttributedString.Key instead"
    severity: error

  deprecated_nsdate:
    name: "Deprecated NSDate"
    regex: '\bNSDate\('
    message: "Use Date instead of NSDate"
    severity: warning

  hardcoded_credentials:
    name: "Hardcoded Credentials"
    regex: '(?i)\b(pass(word)?|passwd|token|key|secret|access|api[_-]?key)\b\s*[:=]\s*["'']([A-Za-z0-9_\-]{8,})["'']'
    message: "Avoid hardcoding credentials (passwords, tokens, keys, secrets, etc.). Use secure storage."
    severity: error
